export const mealsConstants = {
    WEEK_REQUEST: 'MEALS_WEEK_REQUEST',
    WEEK_SUCCESS: 'MEALS_WEEK_SUCCESS',
    WEEK_FAILURE: 'MEALS_WEEK_FAILURE',

    DAILY_REQUEST: 'MEALS_DAILY_REQUEST',
    DAILY_SUCCESS: 'MEALS_DAILY_SUCCESS',
    DAILY_FAILURE: 'MEALS_DAILY_FAILURE',


    ADD_FAVORITE_REQUEST: 'ADD_FAVORITE_REQUEST',
    ADD_FAVORITE_SUCCESS: 'ADD_FAVORITE_SUCCESS',
    ADD_FAVORITE_FAILURE: 'ADD_FAVORITE_FAILURE',


    REMOVE_FAVORITE_REQUEST: 'REMOVE_FAVORITE_REQUEST',
    REMOVE_FAVORITE_SUCCESS: 'REMOVE_FAVORITE_SUCCESS',
    REMOVE_FAVORITE_FAILURE: 'REMOVE_FAVORITE_FAILURE',


    SWAP_MEAL_REQUEST: 'SWAP_MEAL_REQUEST',
    SWAP_MEAL_SUCCESS: 'SWAP_MEAL_SUCCESS',
    SWAP_MEAL_FAILURE: 'SWAP_MEAL_FAILURE',

    GET_HISTORY_REQUEST: 'GET_HISTORY_REQUEST',
    GET_HISTORY_SUCCESS: 'GET_HISTORY_SUCCESS',
    GET_HISTORY_FAILURE: 'GET_HISTORY_FAILURE',


    GET_FAVORITES_REQUEST: 'GET_FAVORITES_REQUEST',
    GET_FAVORITES_SUCCESS: 'GET_FAVORITES_SUCCESS',
    GET_FAVORITES_FAILURE: 'GET_FAVORITES_FAILURE',


    GET_GROCERY_REQUEST:'GET_GROCERY_REQUEST',
    GET_GROCERY_SUCCESS:'GET_GROCERY_SUCCESS',
    GET_GROCERY_FAILURE:'GET_GROCERY_FAILURE',
}

export const authConstants = {
    LOGIN_REUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT_REUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

export const userConstants = {
    USER_REG_REQUEST: 'USER_REG_REQUEST',
    USER_REG_SUCCESS: 'USER_REG_SUCCESS',
    USER_REG_FAILURE: 'USER_REG_FAILURE',

    USER_CHANGE_SETTINGS_REQUEST: 'USER_CHANGE_SETTINGS_REQUEST',
    USER_CHANGE_SETTINGS_SUCCESS: 'USER_CHANGE_SETTINGS_SUCCESS',
    USER_CHANGE_SETTINGS_FAILURE: 'USER_CHANGE_SETTINGS_FAILURE',
}