export const mealsConstants = {
    SEARCH_REQUEST: 'MEALS_SEARCH_REQUEST',
    SEARCH_SUCCESS: 'MEALS_SEARCH_SUCCESS',
    SEARCH_FAILURE: 'MEALS_SEARCH_FAILURE',

    SET_MEALS_REQUEST: 'SET_MEALS_REQUEST',
    SET_MEALS_SUCCESS: 'SET_MEALS_SUCCESS',
    SET_MEALS_FAILURE: 'SET_MEALS_FAILURE',

    SET_GROCERY_LIST_REQUEST: 'MEALS_SET_GROCERY_LIST_REQUEST',
    SET_GROCERY_LIST_SUCCESS: 'MEALS_SET_GROCERY_LIST_SUCCESS',
    SET_GROCERY_LIST_FAILURE: 'MEALS_SET_GROCERY_LIST_FAILURE',

    SET_MACROS_REQUEST: 'MEALS_SET_MACROS_REQUEST',
    SET_MACROS_SUCESS: 'MEALS_SET_MACROS_SUCCESS',
    SET_MACROS_FAILURE: 'MEALS_SET_MACROS_FAILURE',
}

export const userConstants = {
    USER_REG_REQUEST: 'USER_REG_REQUEST',
    USER_REG_SUCCESS: 'USER_REG_SUCCESS',
    USER_REG_FAILURE: 'USER_REG_FAILURE',

    USER_SIGNUPEMAIL_REQUEST: "USER_SIGNUPEMAIL_REQUEST",
    USER_SIGNUPEMAIL_SUCCESS: "USER_SIGNUPEMAIL_SUCCESS",
    USER_SIGNUPEMAIL_FAILURE: "USER_SIGNUPEMAIL_FAILURE",

}