export const dummyFavoriteList = [{
    label: "Mac and Cheese",               
    image: "//placehold.it/150",             
    source: "",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",             
},{
    label: "Mac and Cheese",               
    image: "//placehold.it/150",             
    source: "",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",    
},{
    label: "Mac and Cheese",               
    image: "//placehold.it/150",             
    source: "",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",    
},{
    label: "Mac and Cheese",               
    image: "//placehold.it/150",             
    source: "",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",    
},{
    label: "Mac and Cheese",               
    image: "//placehold.it/150",             
    source: "",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",    
},{
    label: "Mac and Cheese",               
    image: "//placehold.it/150",             
    source: "",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",    
}     ]