// For Meals Page
const dummyMealOptions = {
    breakfast: {
        recipes: [
            {
                type: 'Breakfast',
                servings: 2,
                image: 'https://www.foodiecrush.com/wp-content/uploads/2018/03/chunkymonkeyporridge.jpg',
                title: 'Chunky Monkey Porridge',
                summary: 'Healthy and flavorful twist to a morning oateal routine. Crunchy texture with nutty and fruity elements add to a wonderful breakfast favorite.',
                pricePerServing: '100',
                readyInMinutes: 15,
            }, {
                type: 'Breakfast',
                servings: 2,
                image: 'https://www.foodiecrush.com/wp-content/uploads/2018/03/chunkymonkeyporridge.jpg',
                title: 'Chunky Monkey Porridge',
                summary: 'Healthy and flavorful twist to a morning oateal routine. Crunchy texture with nutty and fruity elements add to a wonderful breakfast favorite.',
                pricePerServing: '623',
                readyInMinutes: 15,
            }, {
                type: 'Breakfast',
                servings: 2,
                image: 'https://www.foodiecrush.com/wp-content/uploads/2018/03/chunkymonkeyporridge.jpg',
                title: 'Chunky Monkey Porridge',
                summary: 'Healthy and flavorful twist to a morning oateal routine. Crunchy texture with nutty and fruity elements add to a wonderful breakfast favorite.',
                pricePerServing: '600',
                readyInMinutes: 15,
            }, {
                type: 'Breakfast',
                servings: 2,
                image: 'https://www.foodiecrush.com/wp-content/uploads/2018/03/chunkymonkeyporridge.jpg',
                title: 'Chunky Monkey Porridge',
                summary: 'Healthy and flavorful twist to a morning oateal routine. Crunchy texture with nutty and fruity elements add to a wonderful breakfast favorite.',
                pricePerServing: '600',
                readyInMinutes: 15,
            }, {
                type: 'Breakfast',
                servings: 2,
                image: 'https://www.foodiecrush.com/wp-content/uploads/2018/03/chunkymonkeyporridge.jpg',
                title: 'Chunky Monkey Porridge',
                summary: 'Healthy and flavorful twist to a morning oateal routine. Crunchy texture with nutty and fruity elements add to a wonderful breakfast favorite.',
                pricePerServing: '600',
                readyInMinutes: 15,
            }
        ],
        macros: [
            [
                "Calories: 600.20cal",
                "Fat: 30.23g",
                "Cholestral: 20.23mg",
                "Sodium: 100.23mg",
                "Sugar: 8.23g",
                "Protein: 12.23g",
                "Carbohydrates: 30.23g",

            ], [
                "Calories: 600.23cal",
                "Fat: 30.23g",
                "Cholestral: 20.23mg",
                "Sodium: 100.23mg",
                "Sugar: 8.23g",
                "Protein: 12.23g",
                "Carbohydrates: 30.23g",

            ],[
                "Calories: 600cal",
                "Fat: 30g",
                "Cholestral: 20mg",
                "Sodium: 100mg",
                "Sugar: 8g",
                "Protein: 12g",
                "Carbohydrates: 30g",

            ],[
                "Calories: 600cal",
                "Fat: 30g",
                "Cholestral: 20mg",
                "Sodium: 100mg",
                "Sugar: 8g",
                "Protein: 12g",
                "Carbohydrates: 30g",

            ],[
                "Calories: 600cal",
                "Fat: 30g",
                "Cholestral: 20mg",
                "Sodium: 100mg",
                "Sugar: 8g",
                "Protein: 12g",
                "Carbohydrates: 30g",

            ],
        ],
        ingredients: [
            {

            }
        ],
    },
    lunch: {
        recipes: [{
            id: '8',
            type: 'Lunch',
            image: 'https://assets.bonappetit.com/photos/5bcf769603dfa83457bf79a5/1:1/w_1600%2Cc_limit/Kedgeree-16x9-12102018.jpg',
            title: 'Rice Bowls with Flaky Cod',
            servings: 2,
            summary: "Kedgeree often calls for smoked fish, but for a light weeknight meal, we prefer steaming fresh fish right on top of the rice.",
            pricePerServing: '1216',
            readyInMinutes: 15,
        },{
            id: '8',
            type: 'Lunch',
            image: 'https://assets.bonappetit.com/photos/5bcf769603dfa83457bf79a5/1:1/w_1600%2Cc_limit/Kedgeree-16x9-12102018.jpg',
            title: 'Rice Bowls with Flaky Cod',
            servings: 2,
            summary: "Kedgeree often calls for smoked fish, but for a light weeknight meal, we prefer steaming fresh fish right on top of the rice.",
            pricePerServing: '1200',
            readyInMinutes: 15,
        },{
            id: '8',
            type: 'Lunch',
            image: 'https://assets.bonappetit.com/photos/5bcf769603dfa83457bf79a5/1:1/w_1600%2Cc_limit/Kedgeree-16x9-12102018.jpg',
            title: 'Rice Bowls with Flaky Cod',
            servings: 2,
            summary: "Kedgeree often calls for smoked fish, but for a light weeknight meal, we prefer steaming fresh fish right on top of the rice.",
            pricePerServing: '1200',
            readyInMinutes: 15,
        },{
            id: '8',
            type: 'Lunch',
            image: 'https://assets.bonappetit.com/photos/5bcf769603dfa83457bf79a5/1:1/w_1600%2Cc_limit/Kedgeree-16x9-12102018.jpg',
            title: 'Rice Bowls with Flaky Cod',
            servings: 2,
            summary: "Kedgeree often calls for smoked fish, but for a light weeknight meal, we prefer steaming fresh fish right on top of the rice.",
            pricePerServing: '1200',
            readyInMinutes: 15,
        },{
            id: '8',
            type: 'Lunch',
            image: 'https://assets.bonappetit.com/photos/5bcf769603dfa83457bf79a5/1:1/w_1600%2Cc_limit/Kedgeree-16x9-12102018.jpg',
            title: 'Rice Bowls with Flaky Cod',
            servings: 2,
            summary: "Kedgeree often calls for smoked fish, but for a light weeknight meal, we prefer steaming fresh fish right on top of the rice.",
            pricePerServing: '1200',
            readyInMinutes: 15,
        }],
        macros: [
            [
                "Calories: 600cal",
                "Fat: 30g",
                "Cholestral: 20mg",
                "Sodium: 100mg",
                "Sugar: 8g",
                "Protein: 12g",
                "Carbohydrates: 30g",

            ], [
                "Calories: 600cal",
                "Fat: 30g",
                "Cholestral: 20mg",
                "Sodium: 100mg",
                "Sugar: 8g",
                "Protein: 12g",
                "Carbohydrates: 30g",

            ],[
                "Calories: 600cal",
                "Fat: 30g",
                "Cholestral: 20mg",
                "Sodium: 100mg",
                "Sugar: 8g",
                "Protein: 12g",
                "Carbohydrates: 30g",

            ],[
                "Calories: 600cal",
                "Fat: 30g",
                "Cholestral: 20mg",
                "Sodium: 100mg",
                "Sugar: 8g",
                "Protein: 12g",
                "Carbohydrates: 30g",

            ],[
                "Calories: 600cal",
                "Fat: 30g",
                "Cholestral: 20mg",
                "Sodium: 100mg",
                "Sugar: 8g",
                "Protein: 12g",
                "Carbohydrates: 30g",

            ],
        ],
        ingredients: [],
    },
    dinner: {
        recipes: [
            {
                type: 'Breakfast',
                servings: 2,
                image: 'https://www.foodiecrush.com/wp-content/uploads/2018/03/chunkymonkeyporridge.jpg',
                title: 'Chunky Monkey Porridge',
                summary: 'Healthy and flavorful twist to a morning oateal routine. Crunchy texture with nutty and fruity elements add to a wonderful breakfast favorite.',
                pricePerServing: '100',
                readyInMinutes: 15,
            }, {
                type: 'Breakfast',
                servings: 2,
                image: 'https://www.foodiecrush.com/wp-content/uploads/2018/03/chunkymonkeyporridge.jpg',
                title: 'Chunky Monkey Porridge',
                summary: 'Healthy and flavorful twist to a morning oateal routine. Crunchy texture with nutty and fruity elements add to a wonderful breakfast favorite.',
                pricePerServing: '600',
                readyInMinutes: 15,
            }, {
                type: 'Breakfast',
                servings: 2,
                image: 'https://www.foodiecrush.com/wp-content/uploads/2018/03/chunkymonkeyporridge.jpg',
                title: 'Chunky Monkey Porridge',
                summary: 'Healthy and flavorful twist to a morning oateal routine. Crunchy texture with nutty and fruity elements add to a wonderful breakfast favorite.',
                pricePerServing: '649',
                readyInMinutes: 15,
            }, {
                type: 'Breakfast',
                servings: 2,
                image: 'https://www.foodiecrush.com/wp-content/uploads/2018/03/chunkymonkeyporridge.jpg',
                title: 'Chunky Monkey Porridge',
                summary: 'Healthy and flavorful twist to a morning oateal routine. Crunchy texture with nutty and fruity elements add to a wonderful breakfast favorite.',
                pricePerServing: '600',
                readyInMinutes: 15,
            }, {
                type: 'Breakfast',
                servings: 2,
                image: 'https://www.foodiecrush.com/wp-content/uploads/2018/03/chunkymonkeyporridge.jpg',
                title: 'Chunky Monkey Porridge',
                summary: 'Healthy and flavorful twist to a morning oateal routine. Crunchy texture with nutty and fruity elements add to a wonderful breakfast favorite.',
                pricePerServing: '600',
                readyInMinutes: 15,
            }
        ],
        macros: [
            [
                "Calories: 600.20cal",
                "Fat: 30.23g",
                "Cholestral: 20.23mg",
                "Sodium: 100.23mg",
                "Sugar: 8.23g",
                "Protein: 12.23g",
                "Carbohydrates: 30.23g",

            ], [
                "Calories: 600.23cal",
                "Fat: 30.23g",
                "Cholestral: 20.23mg",
                "Sodium: 100.23mg",
                "Sugar: 8.23g",
                "Protein: 12.23g",
                "Carbohydrates: 30.23g",

            ],[
                "Calories: 600cal",
                "Fat: 30g",
                "Cholestral: 20mg",
                "Sodium: 100mg",
                "Sugar: 8g",
                "Protein: 12g",
                "Carbohydrates: 30g",

            ],[
                "Calories: 600cal",
                "Fat: 30g",
                "Cholestral: 20mg",
                "Sodium: 100mg",
                "Sugar: 8g",
                "Protein: 12g",
                "Carbohydrates: 30g",

            ],[
                "Calories: 600cal",
                "Fat: 30g",
                "Cholestral: 20mg",
                "Sodium: 100mg",
                "Sugar: 8g",
                "Protein: 12g",
                "Carbohydrates: 30g",
            ],
        ],
        ingredients: [],
    },
    snacks: {
        recipes: [],
        macros: [],
        ingredients: [],
    }
}

const dummyFavoriteList = [{
    title: "Baked Mac and Cheese",               
    image: "https://www.recipetineats.com/wp-content/uploads/2018/05/Baked-Mac-and-Cheese_3.jpg",             
    source: "",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",             
},{
    title: "Simple Mac and Cheese",               
    image: "https://www.recipetineats.com/wp-content/uploads/2018/05/Baked-Mac-and-Cheese-in-bowl_9-2.jpg",             
    source: "",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",    
},{
    title: "Southern Baked Mac and Cheese",               
    image: "https://www.aberdeenskitchen.com/wp-content/uploads/2019/06/One-Pot-Stovetop-Mac-and-Cheese-7.jpg",             
    source: "Basil and Bubbly",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",    
},{
    title: "One Pot Stove Top Mac and Cheese",               
    image: "https://www.aberdeenskitchen.com/wp-content/uploads/2019/06/One-Pot-Stovetop-Mac-and-Cheese-4.jpg",             
    source: "",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",    
},{
    title: "Chickpea Cheese Sauce Mac and Cheese",               
    image: "https://i2.wp.com/www.healthymidwesterngirl.com/wp-content/uploads/2019/07/Chicpea-Cheese-Sauce-2-6.jpg",             
    source: "Healthy Midwestern Girl",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",    
},{
    title: "Butternut Squash Mac and Cheese",               
    image: "https://s23209.pcdn.co/wp-content/uploads/2018/10/Butternut-Squash-Mac-and-CheeseIMG_6987.jpg",             
    source: "Damn Delicious",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",    
}     ]


const dummyNutritionDaily = {
    dailyCalories: "2500 cal",
    dailyFat: "25g",
    dailyCholestral: "10g",
    dailySodium: "150mg",
    dailySugar: "5g",
    dailyProtein: "15g",
    dailyCarbs: "150g"
}

const dummyWeeklyNutritionDaily = {
    weeklyCalories: "7200 cal",
    weeklyFat: "125g",
    weeklyCholestral: "120g",
    weeklySodium: "5000mg",
    weeklySugar: "55g",
    weeklyProtein: "150g",
    weeklyCarbs: "750g"
}


const dummyMeals = [{
    id: '1',
    url: 'https://www.aberdeenskitchen.com/2019/06/one-pot-stovetop-mac-and-cheese/',                
    title: 'One Pot Stovetop Mac and Cheese',               
    image: 'https://www.aberdeenskitchen.com/wp-content/uploads/2019/06/One-Pot-Stovetop-Mac-and-Cheese-7.jpg',            
    source: 'Basil and Bubbly',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '2',
    url: 'https://damndelicious.net/2018/10/17/butternut-squash-mac-and-cheese/',                
    title: 'Butternut Squash Mac and Cheese',               
    image: 'https://s23209.pcdn.co/wp-content/uploads/2018/10/Butternut-Squash-Mac-and-CheeseIMG_6987.jpg',            
    source: 'Damn Delicious',             
    summary: "Mac and cheese at it’s finest! So creamy, so rich + so amazing yet it’s so much healthier than traditional mac and cheese!",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '3',
    url: 'https://www.recipetineats.com/baked-mac-and-cheese/',                
    title: 'Baked Mac and Cheese',               
    image: 'https://www.recipetineats.com/wp-content/uploads/2018/05/Baked-Mac-and-Cheese_3.jpg',            
    source: 'Recipe Tin Eats',             
    summary: "The ultimate classic Baked Mac and Cheese, with an insane cheesy sauce and topped with an irresistible golden, buttery breadcrumb topping. This is the Macaroni Cheese recipe of your dreams!!",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '4',
    url: 'https://www.recipetineats.com/baked-mac-and-cheese/',                
    title: 'Baked Mac and Cheese',               
    image: 'https://www.recipetineats.com/wp-content/uploads/2018/05/Baked-Mac-and-Cheese_3.jpg',            
    source: 'Recipe Tin Eats',             
    summary: "The ultimate classic Baked Mac and Cheese, with an insane cheesy sauce and topped with an irresistible golden, buttery breadcrumb topping. This is the Macaroni Cheese recipe of your dreams!!",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '5',
    url: 'https://www.aberdeenskitchen.com/2019/06/one-pot-stovetop-mac-and-cheese/',                
    title: 'One Pot Stovetop Mac and Cheese',               
    image: 'https://www.aberdeenskitchen.com/wp-content/uploads/2019/06/One-Pot-Stovetop-Mac-and-Cheese-7.jpg',            
    source: 'Basil and Bubbly',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '6',
    url: 'https://damndelicious.net/2018/10/17/butternut-squash-mac-and-cheese/',                
    title: 'Butternut Squash Mac and Cheese',               
    image: 'https://s23209.pcdn.co/wp-content/uploads/2018/10/Butternut-Squash-Mac-and-CheeseIMG_6987.jpg',            
    source: 'Damn Delicious',             
    summary: "Mac and cheese at it’s finest! So creamy, so rich + so amazing yet it’s so much healthier than traditional mac and cheese!",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '7',
    url: 'https://www.recipetineats.com/baked-mac-and-cheese/',                
    title: 'Baked Mac and Cheese',               
    image: 'https://www.recipetineats.com/wp-content/uploads/2018/05/Baked-Mac-and-Cheese_3.jpg',            
    source: 'Recipe Tin Eats',             
    summary: "The ultimate classic Baked Mac and Cheese, with an insane cheesy sauce and topped with an irresistible golden, buttery breadcrumb topping. This is the Macaroni Cheese recipe of your dreams!!",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '8',
    url: 'https://www.aberdeenskitchen.com/2019/06/one-pot-stovetop-mac-and-cheese/',                
    title: 'One Pot Stovetop Mac and Cheese',               
    image: 'https://www.aberdeenskitchen.com/wp-content/uploads/2019/06/One-Pot-Stovetop-Mac-and-Cheese-7.jpg',            
    source: 'Basil and Bubbly',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '9',
    url: 'https://damndelicious.net/2018/10/17/butternut-squash-mac-and-cheese/',                
    title: 'Butternut Squash Mac and Cheese',               
    image: 'https://s23209.pcdn.co/wp-content/uploads/2018/10/Butternut-Squash-Mac-and-CheeseIMG_6987.jpg',            
    source: 'Damn Delicious',             
    summary: "Mac and cheese at it’s finest! So creamy, so rich + so amazing yet it’s so much healthier than traditional mac and cheese!",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '10',
    type: 'Breakfast',
    url: 'https://www.delish.com/cooking/recipe-ideas/a30899293/migas-recipe/',                
    title: 'Best-Ever Migas',               
    image: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/delish-200212-migas-0104-portrait-pf-1582835980.jpg?crop=1.00xw:0.667xh;0,0.0443xh&resize=980:*',            
    source: 'Delish',             
    summary: "Traditional Mexican breakfast that makes crispy fried tortillas meet scrambled eggs, creating that magical crisp-gone-soggy texture that's irresistibly satisfying.",            
    pricePerServing: '4',     
    readyInMinutes: '40',      
    servings: '2',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',           
},{
    id: '11',
    url: 'https://www.iheartnaptime.net/mediterranean-salad/',                
    title: 'Mediterranean Salad with Creamy Balsamic Dressing',               
    image: 'https://www.iheartnaptime.net/wp-content/uploads/2018/07/mediterranean-salad.jpg',            
    source: 'iHeart Nap Time',             
    summary:  "This Mediterranean salad with creamy balsamic dressing is full of greens, protein and flavor! Comes together super quickly and tastes so fresh and delicious. Plus it’s healthier than most restaurants, too!",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',               
},{
    id: '12',
    type: 'Dinner',
    url: 'https://www.iheartnaptime.net/balsamic-chicken/',                
    title: 'One-Pan Balsamic Chicken and Veggies',               
    image: 'https://www.iheartnaptime.net/wp-content/uploads/2017/02/Sheet-pan-balsamic-chicken-recipe-I-Heart-Naptime-4.jpg',            
    source: 'iHeart Nap Time',             
    summary: "One-Pan Balsamic Chicken And Veggies – A Healthy, EASY And Delicious Dinner Recipe That’s Full Of Flavor! A Meal The Whole Family Will Love!",            
    pricePerServing: '4',     
    readyInMinutes: '40',      
    servings: '2',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',              
},{
    id: '13',
    url: '',                
    title: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '14',
    url: '',                
    title: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '15',
    url: '',                
    title: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '16',
    type: 'Breakfast',
    url: 'https://www.delish.com/cooking/recipe-ideas/a30899293/migas-recipe/',                
    title: 'Best-Ever Migas',               
    image: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/delish-200212-migas-0104-portrait-pf-1582835980.jpg?crop=1.00xw:0.667xh;0,0.0443xh&resize=980:*',            
    source: 'Delish',             
    summary: "Traditional Mexican breakfast that makes crispy fried tortillas meet scrambled eggs, creating that magical crisp-gone-soggy texture that's irresistibly satisfying.",            
    pricePerServing: '4',     
    readyInMinutes: '40',      
    servings: '2',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',               
},{
    id: '17',
    url: 'https://www.iheartnaptime.net/mediterranean-salad/',                
    title: 'Mediterranean Salad with Creamy Balsamic Dressing',               
    image: 'https://www.iheartnaptime.net/wp-content/uploads/2018/07/mediterranean-salad.jpg',            
    source: 'iHeart Nap Time',             
    summary:  "This Mediterranean salad with creamy balsamic dressing is full of greens, protein and flavor! Comes together super quickly and tastes so fresh and delicious. Plus it’s healthier than most restaurants, too!",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',                  
},{
    id: '18',
    type: 'Dinner',
    url: 'https://www.iheartnaptime.net/balsamic-chicken/',                
    title: 'One-Pan Balsamic Chicken and Veggies',               
    image: 'https://www.iheartnaptime.net/wp-content/uploads/2017/02/Sheet-pan-balsamic-chicken-recipe-I-Heart-Naptime-4.jpg',            
    source: 'iHeart Nap Time',             
    summary: "One-Pan Balsamic Chicken And Veggies – A Healthy, EASY And Delicious Dinner Recipe That’s Full Of Flavor! A Meal The Whole Family Will Love!",            
    pricePerServing: '4',     
    readyInMinutes: '40',      
    servings: '2',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',           
},{
    id: '19',
    url: '',                
    title: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '20',
    url: '',                
    title: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '21',
    url: '',                
    title: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
}, ]


const dummyGrocery = [
    "3 potatoes",
    "3 cups brown rice",
    "2 lbs lamb chops",
    "4 sprigs dill",
    "4 carrots",
    "1 cabbage",
    "2 lbs brussel sprouts",
    "1 banana bread mix",
]


// For Home Page
const dummyDailyMeals = [
    { 
        mealNum: 0,
        mealType: "Breakfast",
        price: "7",
        meal: {
            id: '1',
            url: 'https://www.aberdeenskitchen.com/2019/06/one-pot-stovetop-mac-and-cheese/',                
            title: 'One Pot Stovetop Mac and Cheese',               
            image: 'https://www.aberdeenskitchen.com/wp-content/uploads/2019/06/One-Pot-Stovetop-Mac-and-Cheese-7.jpg',            
            source: 'Basil and Bubbly',             
            summary: "Gooey, cheesey, and delicious week day favorite.",            
            pricePerServing: '7',     
            readyInMinutes: '40',      
            servings: '5',                     
        },
        macros:  [
            "Calories: 600.20cal",
            "Fat: 30.23g",
            "Cholestral: 20.23mg",
            "Sodium: 100.23mg",
            "Sugar: 8.23g",
            "Protein: 12.23g",
            "Carbohydrates: 30.23g",
        ]
    } , {
        mealNum: 1,
        mealType: "Lunch",
        price: "7",
        meal: {
            id: '2',
            url: 'https://damndelicious.net/2018/10/17/butternut-squash-mac-and-cheese/',                
            title: 'Butternut Squash Mac and Cheese',               
            image: 'https://s23209.pcdn.co/wp-content/uploads/2018/10/Butternut-Squash-Mac-and-CheeseIMG_6987.jpg',            
            source: 'Damn Delicious',             
            summary: "Mac and cheese at it’s finest! So creamy, so rich + so amazing yet it’s so much healthier than traditional mac and cheese!",            
            pricePerServing: '7',     
            readyInMinutes: '40',      
            servings: '5',            
            calories: '600',            
            carbs: '30',               
            fat: '22',                 
            protein: '8',                      
        },
        macros:  [
            "Calories: 600.20cal",
            "Fat: 30.23g",
            "Cholestral: 20.23mg",
            "Sodium: 100.23mg",
            "Sugar: 8.23g",
            "Protein: 12.23g",
            "Carbohydrates: 30.23g",
    
        ]
    } , {
        mealNum: 2,
        mealType: "Dinner",
        price: "7",
        meal: {
            id: '3',
            url: 'https://www.recipetineats.com/baked-mac-and-cheese/',                
            title: 'Baked Mac and Cheese',               
            image: 'https://www.recipetineats.com/wp-content/uploads/2018/05/Baked-Mac-and-Cheese_3.jpg',            
            source: 'Recipe Tin Eats',             
            summary: "The ultimate classic Baked Mac and Cheese, with an insane cheesy sauce and topped with an irresistible golden, buttery breadcrumb topping. This is the Macaroni Cheese recipe of your dreams!!",            
            pricePerServing: '7',     
            readyInMinutes: '40',      
            servings: '5',            
            calories: '600',            
            carbs: '30',               
            fat: '22',                 
            protein: '8',                      
        },
        macros:  [
            "Calories: 600.20cal",
            "Fat: 30.23g",
            "Cholestral: 20.23mg",
            "Sodium: 100.23mg",
            "Sugar: 8.23g",
            "Protein: 12.23g",
            "Carbohydrates: 30.23g",
    
        ]
    } , {
        mealNum: 3,
        mealType: "Snack",
        price: "7",
        meal: {
            id: '4',
            url: 'https://www.recipetineats.com/baked-mac-and-cheese/',                
            title: 'Baked Mac and Cheese',               
            image: 'https://www.recipetineats.com/wp-content/uploads/2018/05/Baked-Mac-and-Cheese_3.jpg',            
            source: 'Recipe Tin Eats',             
            summary: "The ultimate classic Baked Mac and Cheese, with an insane cheesy sauce and topped with an irresistible golden, buttery breadcrumb topping. This is the Macaroni Cheese recipe of your dreams!!",            
            pricePerServing: '7',     
            readyInMinutes: '40',      
            servings: '5',            
            calories: '600',            
            carbs: '30',               
            fat: '22',                 
            protein: '8',                            
        },
        macros:  [
            "Calories: 600.20cal",
            "Fat: 30.23g",
            "Cholestral: 20.23mg",
            "Sodium: 100.23mg",
            "Sugar: 8.23g",
            "Protein: 12.23g",
            "Carbohydrates: 30.23g",
    
        ]
    } , {
        mealNum: 4,
        mealType: "Snack",
        price: "7",
        meal: {
            id: '5',
            url: 'https://www.aberdeenskitchen.com/2019/06/one-pot-stovetop-mac-and-cheese/',                
            title: 'One Pot Stovetop Mac and Cheese',               
            image: 'https://www.aberdeenskitchen.com/wp-content/uploads/2019/06/One-Pot-Stovetop-Mac-and-Cheese-7.jpg',            
            source: 'Basil and Bubbly',             
            summary: "Gooey, cheesey, and delicious week day favorite.",            
            pricePerServing: '7',     
            readyInMinutes: '40',      
            servings: '5',            
            calories: '600',            
            carbs: '30',               
            fat: '22',                 
            protein: '8',                         
        },
        macros:  [
            "Calories: 600.20cal",
            "Fat: 30.23g",
            "Cholestral: 20.23mg",
            "Sodium: 100.23mg",
            "Sugar: 8.23g",
            "Protein: 12.23g",
            "Carbohydrates: 30.23g",
    
        ]
    } , {
        mealNum: 5,
        mealType: "Snack",
        price: "7",
        meal: {
            id: '6',
            url: 'https://damndelicious.net/2018/10/17/butternut-squash-mac-and-cheese/',                
            title: 'Butternut Squash Mac and Cheese',               
            image: 'https://s23209.pcdn.co/wp-content/uploads/2018/10/Butternut-Squash-Mac-and-CheeseIMG_6987.jpg',            
            source: 'Damn Delicious',             
            summary: "Mac and cheese at it’s finest! So creamy, so rich + so amazing yet it’s so much healthier than traditional mac and cheese!",            
            pricePerServing: '7',     
            readyInMinutes: '40',      
            servings: '5',            
            calories: '600',            
            carbs: '30',               
            fat: '22',                 
            protein: '8',                          
        },
        macros:  [
            "Calories: 600.20cal",
            "Fat: 30.23g",
            "Cholestral: 20.23mg",
            "Sodium: 100.23mg",
            "Sugar: 8.23g",
            "Protein: 12.23g",
            "Carbohydrates: 30.23g",
    
        ]
    }
];

const dummyDailyMacros = {
    calories: 2300,
    fat: 80,
    protein: 150,
    carbs: 200,
    fatPercent: 0.186,
    proteinPercent: 0.349,
    carbsPercent: 0.465,
    cholestral: 30,
    sodium: 180,
    sugar: 40,
}


export const dummyData = {
    dummyFavoriteList,
    dummyNutritionDaily,
    dummyWeeklyNutritionDaily,
    dummyGrocery,
    dummyMeals,
    dummyMealOptions,
    dummyDailyMeals,
    dummyDailyMacros,
}