


const dummyFavoriteList = [{
    label: "Mac and Cheese",               
    image: "//placehold.it/150",             
    source: "",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",             
},{
    label: "Mac and Cheese",               
    image: "//placehold.it/150",             
    source: "",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",    
},{
    label: "Mac and Cheese",               
    image: "//placehold.it/150",             
    source: "",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",    
},{
    label: "Mac and Cheese",               
    image: "//placehold.it/150",             
    source: "",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",    
},{
    label: "Mac and Cheese",               
    image: "//placehold.it/150",             
    source: "",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",    
},{
    label: "Mac and Cheese",               
    image: "//placehold.it/150",             
    source: "",              
    calories: "750",        
    carbs: "40g",             
    fat: "15g",                 
    protein: "5g",    
}     ]


const dummyNutritionDaily = {
    dailyCalories: "2500 cal",
    dailyFat: "25g",
    dailyCholestral: "10g",
    dailySodium: "150mg",
    dailySugar: "5g",
    dailyProtein: "15g",
    dailyCarbs: "150g"
}

const dummyWeeklyNutritionDaily = {
    weeklyCalories: "7200 cal",
    weeklyFat: "125g",
    weeklyCholestral: "120g",
    weeklySodium: "5000mg",
    weeklySugar: "55g",
    weeklyProtein: "150g",
    weeklyCarbs: "750g"
}


const dummyMeals = [{
    id: '1',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '2',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '3',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '4',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '5',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '6',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '7',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '8',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '9',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '10',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '11',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '12',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '13',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '14',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '15',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '16',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '17',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '18',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '19',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '20',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
},{
    id: '21',
    url: '',                
    label: 'Mac and Cheese',               
    image: '//placehold.it/150',            
    source: 'All Recipes',             
    summary: "Gooey, cheesey, and delicious week day favorite.",            
    pricePerServing: '7',     
    readyInMinutes: '40',      
    servings: '5',            
    calories: '600',            
    carbs: '30',               
    fat: '22',                 
    protein: '8',             
}, ]


const dummyGrocery = [
    "potatoes",
    "brown rice",
    "lamb chops",
    "dill",
    "carrots",
    "cabbage",
    "brussel sprouts",
    "banana bread mix",
]


const meals = [{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',
    healthLabels: ["Paleo"],
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',
    healthLabels: ["Paleo"],
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',  
    healthLabels: ["Paleo"],      
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',
    healthLabels: ["Paleo"],
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',
    healthLabels: ["Paleo"],
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',    
    healthLabels: ["Paleo"],    
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',    
    healthLabels: ["Paleo"],    
}, {
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',
    healthLabels: ["Paleo"],
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',
    healthLabels: ["Paleo"],
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',  
    healthLabels: ["Paleo"],      
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',
    healthLabels: ["Paleo"],
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',
    healthLabels: ["Paleo"],
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',  
    healthLabels: ["Paleo"],      
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',  
    healthLabels: ["Paleo"],      
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',
    healthLabels: ["Paleo"],
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',
    healthLabels: ["Paleo"],
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',  
    healthLabels: ["Paleo"],      
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',
    healthLabels: ["Paleo"],
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',
    healthLabels: ["Paleo"],
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',   
    healthLabels: ["Paleo"],     
},{
    uri: '112',
    label: 'Mac & Cheese',
    image: '//placehold.it/50',
    source: 'All Recipes',
    url: '',
    yield: '6',
    calories: '890',
    totalWeight: '',
    ingredients: '',
    totalNutrients: '',
    totalDaily: '',   
    healthLabels: ["Paleo"],     
}]

export const dummyData = {
    dummyFavoriteList,
    dummyNutritionDaily,
    dummyWeeklyNutritionDaily,
    dummyGrocery,
    dummyMeals,
}