export const meals = {
    breakfast: [{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',  
        healthLabels: ["Paleo"],      
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',    
        healthLabels: ["Paleo"],    
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',    
        healthLabels: ["Paleo"],    
    }],
    lunch: [{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',  
        healthLabels: ["Paleo"],      
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',  
        healthLabels: ["Paleo"],      
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',  
        healthLabels: ["Paleo"],      
    }],
    dinner: [{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',  
        healthLabels: ["Paleo"],      
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',   
        healthLabels: ["Paleo"],     
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',   
        healthLabels: ["Paleo"],     
    }]
}