export const meals = [{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',  
        healthLabels: ["Paleo"],      
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',    
        healthLabels: ["Paleo"],    
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',    
        healthLabels: ["Paleo"],    
    }, {
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',  
        healthLabels: ["Paleo"],      
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',  
        healthLabels: ["Paleo"],      
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',  
        healthLabels: ["Paleo"],      
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',  
        healthLabels: ["Paleo"],      
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',
        healthLabels: ["Paleo"],
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',   
        healthLabels: ["Paleo"],     
    },{
        uri: '112',
        label: 'Mac & Cheese',
        image: '//placehold.it/50',
        source: 'All Recipes',
        url: '',
        yield: '6',
        calories: '890',
        totalWeight: '',
        ingredients: '',
        totalNutrients: '',
        totalDaily: '',   
        healthLabels: ["Paleo"],     
    }]