import React, { Component } from 'react';
import { Form } from 'react-bootstrap';

export default class Cusine extends Component {
    render() {
        return (
            <Form className={this.props.className}>
                <Form.Check
                    custom
                    type='checkbox'
                    id='African'
                    name="cusine"
                    label="African"
                    value="African"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='American'
                    name="cusine"
                    label="American"
                    value="American"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='British'
                    name="cusine"
                    label="British"
                    value="British"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Cajun'
                    name="cusine"
                    label="Cajun"
                    value="Cajun"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Caribbean'
                    name="cusine"
                    label="Caribbean"
                    value="Caribbean"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Chinese'
                    name="cusine"
                    label="Chinese"
                    value="Chinese"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Eastern European'
                    name="cusine"
                    label="Eastern European"
                    value="Eastern European"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='European'
                    name="cusine"
                    label="European"
                    value="European"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='French'
                    name="cusine"
                    label="French"
                    value="French"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='German'
                    name="cusine"
                    label="German"
                    value="German"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Greek'
                    name="cusine"
                    label="Greek"
                    value="Greek"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Irish'
                    name="cusine"
                    label="Irish"
                    value="Irish"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Italian'
                    name="cusine"
                    label="Italian"
                    value="Italian"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Japanese'
                    name="cusine"
                    label="Japanese"
                    value="Japanese"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Jewish'
                    name="cusine"
                    label="Jewish"
                    value="Jewish"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Korean'
                    name="cusine"
                    label="Korean"
                    value="Korean"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Latin American'
                    name="cusine"
                    label="Latin American"
                    value="Latin American"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Mediterranean'
                    name="cusine"
                    label="Mediterranean"
                    value="Mediterranean"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Mexican'
                    name="cusine"
                    label="Mexican"
                    value="Mexican"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Middle Eastern'
                    name="cusine"
                    label="Middle Eastern"
                    value="Middle Eastern"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Nordic'
                    name="cusine"
                    label="Nordic"
                    value="Nordic"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Southern'
                    name="cusine"
                    label="Southern"
                    value="Southern"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Spanish'
                    name="cusine"
                    label="Spanish"
                    value="Spanish"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Thai'
                    name="cusine"
                    label="Thai"
                    value="Thai"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />
                <Form.Check
                    custom
                    type='checkbox'
                    id='Vietnamese'
                    name="cusine"
                    label="Vietnamese"
                    value="Vietnamese"
                    onChange={this.props.handleChange}
                    className="BodyFontD"
                />

        </Form>
        )
    }
}
