import React, { Component } from 'react';
import { Form } from 'react-bootstrap';

export default class DietLifestyle extends Component {
    render() {
        const type = this.props.type;
        return (
            <Form className={this.props.className}>
                <Form.Check
                    custom
                    type={type}
                    name="diet"
                    id='gluten1'
                    label='Gluten Free'
                    value="Gluten Free"
                    onChange={this.props.handleChange}
                    style={{marginBottom:5}}
                    className="BodyFontE"
                />
                <Form.Check
                    custom
                    type={type}
                    name="diet"
                    id='keto'
                    label='Keto'
                    value="Ketogenic"
                    onChange={this.props.handleChange}
                    style={{marginBottom:5}}
                    className="BodyFontE"
                />
                <Form.Check
                    custom
                    type={type}
                    name="diet"
                    id='vegetarian'
                    label='Vegetarian'
                    value="Vegetarian"
                    onChange={this.props.handleChange}
                    style={{marginBottom:5}}
                    className="BodyFontE"
                />
                <Form.Check
                    custom
                    type={type}
                    name="diet"
                    id='lacto-vegetarain'
                    label='Lacto-Vegetarian'
                    value="Lacto-Vegetarian"
                    onChange={this.props.handleChange}
                    style={{marginBottom:5}}
                    className="BodyFontE"
                />
                <Form.Check
                custom
                    type={type}
                    name="diet"
                    id='ovo-vegetarian'
                    label='Ovo-Vegetarian'
                    value="Ovo-Vegetarian"
                    onChange={this.props.handleChange}
                    style={{marginBottom:5}}
                    className="BodyFontE"
                />
                <Form.Check
                custom
                    type={type}
                    name="diet"
                    id='vegan'
                    label='Vegan'
                    value="Vegan"
                    onChange={this.props.handleChange}
                    style={{marginBottom:5}}
                    className="BodyFontE"
                />
                <Form.Check
                custom
                    type={type}
                    name="diet"
                    id='pescetarian'
                    label='Pescetarian'
                    value="Pescetarian"
                    onChange={this.props.handleChange}
                    style={{marginBottom:5}}
                    className="BodyFontE"
                />
                <Form.Check
                custom
                    type={type}
                    name="diet"
                    id='paleo'
                    label='Paleo'
                    value="Paleo"
                    onChange={this.props.handleChange}
                    style={{marginBottom:5}}
                    className="BodyFontE"
                />
                <Form.Check
                custom
                    type={type}
                    name="diet"
                    id='Primal'
                    label='Primal'
                    value="Primal"
                    onChange={this.props.handleChange}
                    style={{marginBottom:5}}
                    className="BodyFontE"
                />
                <Form.Check
                custom
                    type={type}
                    name="diet"
                    id='whole30'
                    label='Whole30'
                    value="Whole30"
                    onChange={this.props.handleChange}
                    style={{marginBottom:5}}
                    className="BodyFontE"
                />
            </Form>
        )
    }   
}
